---
services:
  database:
    image: redis
    network_mode: bridge
  frontend:
    image: nginx
    network_mode: bridge
    ports:
    - published: 80
      target: 80      
version: '3.9'
  
