services:
        phpmyadmin:
                image: corbinu/docker-phpmyadmin
                environment:
                        MYSQL_ROOT_PASSWORD: learn
                        MYSQL_USERNAME: root
                links:
                        - "wordpress_db:mysql"
                ports:
                        - "8282:80"
        wordpress:
                image: wordpress
                links:
                        - "wordpress_db:mysql"
                ports:
                        - "8383:80"
        wordpress_db:
                image: mariadb
                environment:
                        MARIADB_ROOT_PASSWORD: learn
version: '3.0'


